# Generated by Django 5.2.4 on 2025-09-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="lang",
            field=models.CharField(
                choices=[("en", "en"), ("pt", "pt"), ("es", "es")],
                default="en",
                max_length=2,
            ),
        ),
    ]
